# Generated by Django 3.2 on 2023-05-23 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('orange_chocolate', 'Chocolat Orange'), ('maple_sirup_nuts', "Sirop d'érable Noix"), ('chocolate_mint', 'Menthe Chocolat'), ('vanilla_strawberry_chocolate', 'Vanille Fraise Chocolat'), ('white_chocolate_raspberry', 'Chocolat blanc Framboise')], help_text='Icecream parfum', max_length=255)),
                ('price', models.IntegerField(default=2, help_text='ice cream scoop price')),
                ('stock', models.IntegerField(default=40, help_text='ice cream scoop quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Command number', max_length=10, unique=True)),
                ('recipe', models.CharField(help_text='Command recipe', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
