# Generated by Django 3.2 on 2023-05-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='id',
        ),
        migrations.AlterField(
            model_name='command',
            name='code',
            field=models.CharField(help_text='Command number', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='recipe',
            field=models.JSONField(default=dict, help_text='Command recipe'),
        ),
    ]
