# Generated by Django 3.2 on 2023-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230523_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_price',
            field=models.IntegerField(default=0, help_text='Command price'),
        ),
    ]
