# Generated by Django 3.2 on 2023-05-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_command_command_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user',
        ),
    ]
